export const S_WHATSAPP_NET: "@s.whatsapp.net";
export const OFFICIAL_BIZ_JID: "16505361212@c.us";
export const SERVER_JID: "server@c.us";
export const PSA_WID: "0@c.us";
export const STORIES_JID: "status@broadcast";
export const META_AI_JID: "13135550002@c.us";
export function jidEncode(user: any, server: any, device: any, agent: any): string;
export function jidDecode(jid: any): {
    server: any;
    user: any;
    domainType: number;
    device: number | undefined;
} | undefined;
export function areJidsSameUser(jid1: any, jid2: any): boolean;
export function isJidMetaIa(jid: any): any;
export function isJidUser(jid: any): any;
export function isLidUser(jid: any): any;
export function isJidBroadcast(jid: any): any;
export function isJidGroup(jid: any): any;
export function isJidStatusBroadcast(jid: any): boolean;
export function isJidNewsletter(jid: any): any;
export function isJidBot(jid: any): any;
export function jidNormalizedUser(jid: any): string;
