export function makeBusinessSocket(config: any): {
    logger: any;
    getOrderDetails: (orderId: any, tokenBase64: any) => Promise<{
        price: {
            total: number;
            currency: any;
        };
        products: any;
    }>;
    getCatalog: ({ jid, limit, cursor }: {
        jid: any;
        limit: any;
        cursor: any;
    }) => Promise<{
        products: any;
        nextPageCursor: any;
    }>;
    getCollections: (jid: any, limit?: number) => Promise<{
        collections: any;
    }>;
    productCreate: (create: any) => Promise<{
        id: any;
        imageUrls: {
            requested: any;
            original: any;
        };
        reviewStatus: {
            whatsapp: any;
        };
        availability: string;
        name: any;
        retailerId: any;
        url: any;
        description: any;
        price: number;
        currency: any;
        isHidden: boolean;
    }>;
    productDelete: (productIds: any) => Promise<{
        deleted: number;
    }>;
    productUpdate: (productId: any, update: any) => Promise<{
        id: any;
        imageUrls: {
            requested: any;
            original: any;
        };
        reviewStatus: {
            whatsapp: any;
        };
        availability: string;
        name: any;
        retailerId: any;
        url: any;
        description: any;
        price: number;
        currency: any;
        isHidden: boolean;
    }>;
    fileName: string;
    sendMessageAck: ({ tag, attrs, content }: {
        tag: any;
        attrs: any;
        content: any;
    }, errorCode: any) => Promise<void>;
    sendRetryRequest: (node: any, forceIncludeKeys?: boolean) => Promise<void>;
    rejectCall: (callId: any, callFrom: any) => Promise<void>;
    fetchMessageHistory: (count: any, oldestMsgKey: any, oldestMsgTimestamp: any) => Promise<any>;
    requestPlaceholderResend: (messageKey: any) => Promise<any>;
    getPrivacyTokens: (jids: any) => Promise<any>;
    assertSessions: (jids: any, force: any) => Promise<boolean>;
    relayMessage: (jid: any, message: any, options: any, attempts?: number, maxRetries?: number) => Promise<any>;
    sendReceipt: (jid: any, participant: any, messageIds: any, type: any) => Promise<void>;
    sendReceipts: (keys: any, type: any) => Promise<void>;
    readMessages: (keys: any) => Promise<void>;
    refreshMediaConn: (forceGet?: boolean) => Promise<any>;
    waUploadToServer: (filePath: any, { mediaType, fileEncSha256B64, timeoutMs }: {
        mediaType: any;
        fileEncSha256B64: any;
        timeoutMs: any;
    }) => Promise<{
        mediaUrl: any;
        directPath: any;
    }>;
    fetchPrivacySettings: (force?: boolean) => Promise<any>;
    sendPeerDataOperationMessage: (pdoMessage: any) => Promise<any>;
    createParticipantNodes: (jids: any, message: any, extraAttrs: any) => Promise<{
        nodes: any[];
        shouldIncludeDeviceIdentity: boolean;
    }>;
    getUSyncDevices: (jids: any, useCache: any, ignoreZeroDevices: any) => Promise<any[]>;
    updateMediaMessage: (message: any) => Promise<any>;
    sendMessage: (jid: any, content: any, options?: {}) => Promise<import("..").proto.WebMessageInfo | undefined>;
    sendAlbumMessage: (jid: any, medias: any, options?: {}) => Promise<import("..").proto.WebMessageInfo>;
    extractNewsletterMetadata: (node: any, isCreate: any) => {
        id: any;
        state: any;
        creation_time: number;
        name: any;
        nameTime: number;
        description: any;
        descriptionTime: number;
        invite: any;
        handle: any;
        picture: any;
        preview: any;
        reaction_codes: any;
        subscribers: number;
        verification: any;
        viewer_metadata: any;
    };
    subscribeNewsletterUpdates: (jid: any) => Promise<any>;
    newsletterReactionMode: (jid: any, mode: any) => Promise<void>;
    newsletterUpdateDescription: (jid: any, description: any) => Promise<void>;
    newsletterUpdateName: (jid: any, name: any) => Promise<void>;
    newsletterUpdatePicture: (jid: any, content: any) => Promise<void>;
    newsletterRemovePicture: (jid: any) => Promise<void>;
    newsletterAction: (jid: any, type: any) => Promise<void>;
    newsletterCreate: (name: any, description: any) => Promise<{
        id: any;
        state: any;
        creation_time: number;
        name: any;
        nameTime: number;
        description: any;
        descriptionTime: number;
        invite: any;
        handle: any;
        picture: any;
        preview: any;
        reaction_codes: any;
        subscribers: number;
        verification: any;
        viewer_metadata: any;
    }>;
    newsletterMetadata: (type: any, key: any, role: any) => Promise<{
        id: any;
        state: any;
        creation_time: number;
        name: any;
        nameTime: number;
        description: any;
        descriptionTime: number;
        invite: any;
        handle: any;
        picture: any;
        preview: any;
        reaction_codes: any;
        subscribers: number;
        verification: any;
        viewer_metadata: any;
    }>;
    newsletterAdminCount: (jid: any) => Promise<any>;
    newsletterChangeOwner: (jid: any, user: any) => Promise<void>;
    newsletterPromote: (jid: any, user: any) => Promise<void>;
    newsletterDemote: (jid: any, user: any) => Promise<void>;
    newsletterDelete: (jid: any) => Promise<void>;
    newsletterReactMessage: (jid: any, serverId: any, code: any) => Promise<void>;
    newsletterFetchMessages: (type: any, key: any, count: any, after: any) => Promise<{
        server_id: any;
        views: number;
        reactions: any;
    }[]>;
    newsletterFetchUpdates: (jid: any, count: any, after: any, since: any) => Promise<{
        server_id: any;
        views: number;
        reactions: any;
    }[]>;
    newsletterWMexQuery: (jid: any, queryId: any, content: any) => Promise<any>;
    newsletterQuery: (jid: any, type: any, content: any) => Promise<any>;
    groupQuery: (jid: any, type: any, content: any) => Promise<any>;
    groupMetadata: (jid: any) => Promise<{
        desc: any;
        descId: any;
        descOwner: string | undefined;
        descOwnerLid: string | undefined;
        descTime: number | undefined;
        linkedParent: any;
        restrict: boolean;
        announce: boolean;
        isCommunity: boolean;
        isCommunityAnnounce: boolean;
        joinApprovalMode: boolean;
        memberAddMode: boolean;
        participants: any;
        ephemeralDuration: number | undefined;
        ownerLid?: string | undefined;
        subjectTime: number | undefined;
        size: any;
        creation: number | undefined;
        owner: string;
        subjectOwnerLid?: string | undefined;
        id: any;
        addressingMode: any;
        subject: any;
        subjectOwner: string;
    }>;
    groupCreate: (subject: any, participants: any) => Promise<{
        desc: any;
        descId: any;
        descOwner: string | undefined;
        descOwnerLid: string | undefined;
        descTime: number | undefined;
        linkedParent: any;
        restrict: boolean;
        announce: boolean;
        isCommunity: boolean;
        isCommunityAnnounce: boolean;
        joinApprovalMode: boolean;
        memberAddMode: boolean;
        participants: any;
        ephemeralDuration: number | undefined;
        ownerLid?: string | undefined;
        subjectTime: number | undefined;
        size: any;
        creation: number | undefined;
        owner: string;
        subjectOwnerLid?: string | undefined;
        id: any;
        addressingMode: any;
        subject: any;
        subjectOwner: string;
    }>;
    groupLeave: (id: any) => Promise<void>;
    groupUpdateSubject: (jid: any, subject: any) => Promise<void>;
    groupRequestParticipantsList: (jid: any) => Promise<any>;
    groupRequestParticipantsUpdate: (jid: any, participants: any, action: any) => Promise<any>;
    groupParticipantsUpdate: (jid: any, participants: any, action: any) => Promise<any>;
    groupUpdateDescription: (jid: any, description: any) => Promise<void>;
    groupInviteCode: (jid: any) => Promise<any>;
    groupRevokeInvite: (jid: any) => Promise<any>;
    groupAcceptInvite: (code: any) => Promise<any>;
    groupRevokeInviteV4: (groupJid: any, invitedJid: any) => Promise<boolean>;
    groupAcceptInviteV4: (...args: any[]) => Promise<any>;
    groupGetInviteInfo: (code: any) => Promise<{
        desc: any;
        descId: any;
        descOwner: string | undefined;
        descOwnerLid: string | undefined;
        descTime: number | undefined;
        linkedParent: any;
        restrict: boolean;
        announce: boolean;
        isCommunity: boolean;
        isCommunityAnnounce: boolean;
        joinApprovalMode: boolean;
        memberAddMode: boolean;
        participants: any;
        ephemeralDuration: number | undefined;
        ownerLid?: string | undefined;
        subjectTime: number | undefined;
        size: any;
        creation: number | undefined;
        owner: string;
        subjectOwnerLid?: string | undefined;
        id: any;
        addressingMode: any;
        subject: any;
        subjectOwner: string;
    }>;
    groupToggleEphemeral: (jid: any, ephemeralExpiration: any) => Promise<void>;
    groupSettingUpdate: (jid: any, setting: any) => Promise<void>;
    groupMemberAddMode: (jid: any, mode: any) => Promise<void>;
    groupJoinApprovalMode: (jid: any, mode: any) => Promise<void>;
    groupFetchAllParticipating: () => Promise<{}>;
    getBotListV2: () => Promise<{
        jid: any;
        personaId: any;
    }[]>;
    processingMutex: {
        mutex(code: any): Promise<void>;
    };
    upsertMessage: (...args: any[]) => Promise<any>;
    appPatch: (patchCreate: any) => Promise<void>;
    sendPresenceUpdate: (type: any, toJid: any) => Promise<void>;
    presenceSubscribe: (toJid: any, tcToken: any) => any;
    profilePictureUrl: (jid: any, type: string | undefined, timeoutMs: any) => Promise<any>;
    onWhatsApp: (...jids: any[]) => Promise<any>;
    fetchBlocklist: () => Promise<any>;
    fetchStatus: (...jids: any[]) => Promise<any>;
    fetchDisappearingDuration: (...jids: any[]) => Promise<any>;
    fetchLidByJids: (...jids: any[]) => Promise<any>;
    updateProfilePicture: (jid: any, content: any) => Promise<void>;
    removeProfilePicture: (jid: any) => Promise<void>;
    updateProfileStatus: (status: any) => Promise<void>;
    updateProfileName: (name: any) => Promise<void>;
    updateBlockStatus: (jid: any, action: any) => Promise<void>;
    updateCallPrivacy: (value: any) => Promise<void>;
    updateMessagesPrivacy: (value: any) => Promise<void>;
    updateLastSeenPrivacy: (value: any) => Promise<void>;
    updateOnlinePrivacy: (value: any) => Promise<void>;
    updateProfilePicturePrivacy: (value: any) => Promise<void>;
    updateStatusPrivacy: (value: any) => Promise<void>;
    updateReadReceiptsPrivacy: (value: any) => Promise<void>;
    updateGroupsAddPrivacy: (value: any) => Promise<void>;
    updateDefaultDisappearingMode: (duration: any) => Promise<void>;
    getBusinessProfile: (jid: any) => Promise<{
        wid: any;
        address: any;
        description: any;
        website: any[];
        email: any;
        category: any;
        business_hours: {
            timezone: any;
            business_config: any;
        };
    } | undefined>;
    resyncAppState: (...args: any[]) => Promise<any>;
    chatModify: (mod: any, jid: any) => Promise<void>;
    cleanDirtyBits: (type: any, fromTimestamp: any) => Promise<void>;
    addLabel: (jid: any, labels: any) => Promise<void>;
    addChatLabel: (jid: any, labelId: any) => Promise<void>;
    removeChatLabel: (jid: any, labelId: any) => Promise<void>;
    addMessageLabel: (jid: any, messageId: any, labelId: any) => Promise<void>;
    removeMessageLabel: (jid: any, messageId: any, labelId: any) => Promise<void>;
    star: (jid: any, messages: any, star: any) => Promise<void>;
    executeUSyncQuery: (usyncQuery: any) => Promise<any>;
    ws: import("./Client").WebSocketClient;
    ev: {
        process(handler: any): () => void;
        emit(event: any, evData: any): any;
        isBuffering(): boolean;
        buffer: () => void;
        flush: (force?: boolean) => boolean;
        createBufferedFunction(work: any): (...args: any[]) => Promise<any>;
        on: (...args: any[]) => any;
        off: (...args: any[]) => any;
        removeAllListeners: (...args: any[]) => any;
    };
};
