export function makeGroupsSocket(config: any): any;
export function extractGroupMetadata(result: any): {
    id: any;
    notify: any;
    addressingMode: any;
    subject: any;
    subjectOwner: any;
    subjectOwnerPn: any;
    subjectTime: number;
    size: any;
    creation: number;
    owner: any;
    ownerPn: any;
    owner_country_code: any;
    desc: any;
    descId: any;
    descOwner: any;
    descOwnerPn: any;
    descTime: number | undefined;
    linkedParent: any;
    restrict: boolean;
    announce: boolean;
    isCommunity: boolean;
    isCommunityAnnounce: boolean;
    joinApprovalMode: boolean;
    memberAddMode: boolean;
    participants: any;
    ephemeralDuration: number | undefined;
};
